name: pr-build

on:
  pull_request:
  merge_group:

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22.20.0

      - run: echo "pnpm_version=$(node -p 'require(`./Builder/package.json`).packageManager.replace(/^pnpm@/, ``)')" >> $GITHUB_OUTPUT
        id: pnpm-version

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}

      - run: pnpm install
        working-directory: Builder

      - run: pnpm lint
        working-directory: Builder

      - name: Install and Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Find globals
        uses: LiangYuxuan/action-findglobals@v2
        with:
          find-args: "! -path \"./AddOn/Libs/*\""

      - name: Create Retail Package
        uses: BigWigsMods/packager@v2
        with:
          args: "-d -z"

      - uses: actions/upload-artifact@v4
        with:
          name: pull-request-${{ github.event.number }}-${{ github.sha }}
          path: .release/
