name: pr-build

on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: corepack enable

      - run: pnpm install
        working-directory: Builder

      - run: pnpm lint
        working-directory: Builder

      - name: Install and Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Find globals
        uses: LiangYuxuan/action-findglobals@master
        with:
          find-args: "! -path \"./AddOn/Libs/*\""
