name: regenerate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  regenerate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: echo "pnpm_version=$(node -p 'require(`./Builder/package.json`).packageManager.replace(/^pnpm@/, ``)')" >> $GITHUB_OUTPUT
        id: pnpm-version

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}

      - run: pnpm install
        working-directory: Builder

      - run: pnpm lint
        working-directory: Builder

      - run: pnpm start
        working-directory: Builder
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Regenerate
          commit-message: "chore: regenerate"
          branch: regenerate
          delete-branch: true
