name: Update library

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch new library
        run: make libs

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update library
          commit-message: "test: update library"
          branch: update-library
          delete-branch: true
