name: update-library

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: BigWigsMods/packager@v2
        with:
          args: "-c -d -z"

      - run: cp -a .release/ElvUI_RhythmBox/Libs/* AddOn/Libs/

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: "AddOn/Libs/*"
          title: Update library
          commit-message: "build: update library"
          branch: update-library
          delete-branch: true
